/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gestoresposicionamento;

import java.awt.Color;
import java.awt.FlowLayout;
import javax.swing.JButton;
import javax.swing.JFrame;


/**
 *
 * @author Duarte Nuno Amorim
 */
public class FlowLayout1 extends javax.swing.JFrame {

    private static final int LARGURA_JANELA = 400;
    private static final int ALTURA_JANELA = 200;
    
    /**
     * Creates new form FlowLayout1
     */
    public FlowLayout1(String titulo) {
        super(titulo);
        getContentPane().setBackground(Color.LIGHT_GRAY);
        
        FlowLayout f1 = new FlowLayout();
        setLayout(f1);
        
        adicionarBotoes();
        
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(LARGURA_JANELA, ALTURA_JANELA);
        setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlowLayout1 jan = new FlowLayout1("FlowLayout");
    }
    
    private void adicionarBotoes() {
        JButton b1 = new JButton("Um");
        JButton b2 = new JButton("Dois");
        JButton b3 = new JButton("Três");
        JButton b4 = new JButton("Quatro");
        JButton b5 = new JButton("Cinco");
        JButton b6 = new JButton("Seis");
        JButton b7 = new JButton("Sete");
        
        add(b1);
        add(b2);
        add(b3);
        add(b4);
        add(b5);
        add(b6);
        add(b7);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
